---
- name: Handling multi-item dictionary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize switch data
      ansible.builtin.set_fact:
        # switch_health_check: "{{ switch_health_check | default({}) | combine({ switch_item: {'nodeState': 'NOENTRY', 'nodeName': 'NOENTRY'}}, recursive=True) }}"
        switch_health_check: "{{ switch_health_check | default({}) | combine({'switch1': {'nodeState': 'NOENTRY', 'nodeName': 'NOENTRY'},'switch2': {'nodeState': 'NOENTRY', 'nodeName': 'NOENTRY'},'switch3': {'nodeState': 'NOENTRY', 'nodeName': 'NOENTRY'},'switch4': {'nodeState': 'NOENTRY', 'nodeName': 'NOENTRY'}}, recursive=True) }}"
      # with_items:
      #   - 'switch1'
      #   - 'switch2'
      #   - 'switch3'
      #   - 'switch4'
      # loop_control:
      #   loop_var: switch_item
      #   label: "{{ switch_item }}"
    - name: Print dict
      debug:
        msg: "{{ switch_health_check }}"