---
- name: Floating Point Operation
  hosts: localhost
  gather_facts: false
  vars:
    tagname: 1.1
    increment: 0.4
  tasks:
    - name: Print tagname
      debug:
        msg: "{{ tagname }}"

    - name: Increment tagname value
      set_fact:
        #tagname: "{{ tagname | float }}" #" + 0.1  }}"
        tagname: "{{ tagname | float  + increment | float }}"

    - name: Print the String
      debug:
        msg: "{{ tagname }}"


    # - name: "New Task Added"
    #   ansible.builtin.debug:
    #     msg: "This is a new task added for demo"