---
- name: "Multi Dict Loop"
  hosts: localhost
  gather_facts: false
  vars:
    dict_var1:
      cmd1: "mycmd1"
      cmd2: "mycmd2"
      cmd3: "mycmd3"
    dict_var2:
      file1: "myfile1"
      file2: "myfile2"
      file3: "myfile3"
  tasks:
    - debug:
        msg: "{{ dict_var1 }}"
    - name: "Loop with multiple list"
      debug:
        msg: "{{ item[0].value }} {{ item[1].value }}"
      with_nested:
        - '{{ dict_var1 | dict2items }}'
        - '{{ dict_var2 | dict2items }}'
