---
- name: Ansible Lightspeed Demo
  hosts: RHEL9
  tasks:
    # - name: Create Service Object-Group in Cisco ASA

    - name: Cisco ASA - Write current configuration to memory
      ansible.builtin.command: /usr/sbin/asa_write_memory
      become: true
      become_user: root
      changed_when: false
