---
- name: Download files from Internet or Intranet
  hosts: nodes
  become: true
  tasks:
    - name: Download python pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /home/devops/get-pip.py
        mode: '0755'
