---
- name: Add block of text to a file
  hosts: nodes
  become: true
  tasks:
    - name: Add a block of text to an existing file
      blockinfile:
        path: /home/devops/demo-text-file.txt
        block: |
          This block of text consists of two lines.
          They have been added by Ansible using the blockinfile module.
          Hello
        state: present
        insertbefore: 'line 2'
