---
- name: Using the file module to ensure SELinux file context
  hosts: nodes
  become: true
  tasks:
    #- name:  SELinux file context is set to defaults
    #  file:
    #    path: /home/ansible/demo-text-file.txt
    #    seuser: _default
    #    serole: _default
    #    setype: _default
    #    selevel: _default

    - name: Create a symbolic link
      file:
        src: /home/devops/demo-text-file.txt
        dest: /home/devops/link-to-demo.txt
        owner: devops
        group: devops
        state: link
    
    - name: Create a new directory if it does not exist
      file:
        path: /home/devops/new-dir
        state: directory
        mode: '0755'
