---
version: 1

build_arg_defaults:
  # EE_BASE_IMAGE: 'automationhub22-1.lab.local/ee-minimal-rhel8:latest'
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:1.0.0-395'
ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements-azure.txt

additional_build_steps:
#  prepend:
#    - RUN pip3 install --upgrade pip setuptools
  append:
    - RUN microdnf install which
